### ISSUE TITLE
trailing-commas messes up objects in function calls

### ISSUE THREAD

**Issue by lencioni** [cpojer/js-codemod#27]
Given the following code:

```js
foo({
  bar: 'bar'
});
```

the trailing-commas transform produces:

```js
foo(
  {
    bar: 'bar',
  },
);
```

The newlines, indentation, and trailing comma after the closing curly are undesirable. This is particularly noticeable when running this transform on a React component using `React.createClass`:

```jsx
import React from 'react';

const Foo = React.createClass({
  render() {
    return <p>foo</p>;
  }
});
```

becomes

```jsx
import React from 'react';

const Foo = React.createClass(
  {
    render() {
      return <p>foo</p>;
    },
  },
);
```

cc: @janicduplessis

**Comment by cpojer** [comment]
yeah this is not great. I think this is actually a recast issue. I was the one to implement trailing comma printing and it isn't perfect. It's somewhere in here: https://github.com/benjamn/recast/blob/master/lib/printer.js#L1659-L1690

I think it is reasonable to not print those newlines when there is only one argument to a function call.

**Comment by cpojer** [comment]
cc @benjamn

**Comment by benjamn** [comment]
Yeah, if there's a single argument, I agree it should begin on the same line as the function call, even if the argument is multi-line, and there should probably not be a trailing comma, though I'm less opinionated about that.

**Comment by cpojer** [comment]
@lencioni @janicduplessis up for some hacking on https://github.com/benjamn/recast ? :)

**Comment by lencioni** [comment]
I think there should not be a trailing comma,

**Comment by lencioni** [comment]
I agree that there should not be a trailing comma, unless the function call is written like:

```js
foo(
  bar,
  baz,
);
```

And this should probably be an option, for folks who can't use [trailing commas in functions](https://jeffmo.github.io/es-trailing-function-commas/) yet.

**Comment by cpojer** [comment]
Oh right, there shouldn't be one on the arguments list, but this transform is about adding them to object expressions.

**Comment by janicduplessis** [comment]
Yea the transform only affects arrays and object litterals. I'll hack on recast this weekend to try to improve the formating.

**Comment by benjamn** [comment]
Awesome, let me know if you get hung up on anything.

**Comment by lencioni** [comment]
@janicduplessis any luck?

**Comment by janicduplessis** [comment]
Yes, I actually found a way to fix this, I just didn't get the time to submit the PR.

Can you try setting wrapColumn to 1 instead of 0 [here](https://github.com/cpojer/js-codemod/blob/master/transforms/trailing-commas.js#L42) see if fixes what you were talking about?

If it does fix it I'll submit the PR tonight.

**Comment by lencioni** [comment]
I added this to the test

```js
foo({
  bar: 'bar'
});
```

and this to the test output:

```js
foo({
  bar: 'bar',
});
```

and changed the `0` to `1`, and the test passed. Thanks!
