### ISSUE TITLE
Do you have a codemod for top-level require() -> ES6 import?

### ISSUE THREAD

**Issue by ide** [cpojer/js-codemod#3]

**Comment by pieterv** [comment]
@ide I saw this one floating around on twitter: https://gist.github.com/jeffpeterson/aaf606f0628009d6eaf4

**Comment by ide** [comment]
@pieterv thanks. (got it working w/a small mod: https://gist.github.com/ide/f3266c3915b0e45dac78)

**Comment by pieterv** [comment]
Nice! @cpojer we really need a lightweight place to store these codemods.

**Comment by cpojer** [comment]
Send me pull requests and I can host them in this repo :)
