### ISSUE TITLE
trailing-commas transform moves trailing comments

### ISSUE THREAD

**Issue by lencioni** [cpojer/js-codemod#34]
Given code like

```js
const foo = {
  bar: true // comment
};
```

the trailing-commas transform moves the comment up:

```js
const foo = {
  // comment
  bar: true,
};
```

It would be nicer if the comment placement was preserved:

```js
const foo = {
  bar: true, // comment
};
```

**Comment by cpojer** [comment]
cc @janicduplessis

**Comment by janicduplessis** [comment]
We'll definitely have to hack on recast to fix this :)

**Comment by cpojer** [comment]
Is there anyone who is willing to take a look at this?

**Comment by cpojer** [comment]
Closing given inactivity. Feel free to send a PR anytime.
