### ISSUE TITLE
Codemods community?

### ISSUE THREAD

**Issue by Daniel15** [cpojer/js-codemod#37]
I was going to create a repo for my own personal codemods, but thought it might be a good idea to instead add them into this repo, so there's lots of useful codemods all in the one place. I thought it'd be nice to have a codemods community project of sorts, where anyone could contribute their codemods. I made a codemods org on Github (https://github.com/codemods) but it's currently blank... What do you think about having this repo live there? :smile:

**Comment by cpojer** [comment]
I think it is fine to keep it here for now.
