### ISSUE TITLE
Add var -> let/const transform

### ISSUE THREAD

**Issue by pieterv** [cpojer/js-codemod#4]
Someone awesome, like @iamdustan, should add a transform to this repo for `var` -> `let`/`const`. Here is the astexplorer transform code that @iamdustan posted: http://felix-kling.de/esprima_ast_explorer/#/tGblyJN52T/4

**Comment by iamdustan** [comment]
Thanks @pieterv :)

Use this one for better results: http://felix-kling.de/esprima_ast_explorer/#/tGblyJN52T/7

1. My regex for opting for `let` over `const` for `Statement`s was waaaaay too aggressive. I switched it to match For/ForIn/Do/DoWhile statements specifically. Probably missed some off hand like ForOf?
2. Assumes that facebook/flow#831 is released.

**Comment by pieterv** [comment]
Cool, thanks for the info! I imagine a lot of people are going to want to do this conversion soon, it would be great to an authoritative source for this transform.

**Comment by iamdustan** [comment]
I’ll aim to get a PR open with some test cases before the weekend. :)

**Comment by pieterv** [comment]
That would be awesome!
