### ISSUE TITLE
trailing-commas forces whitespace to spaces

### ISSUE THREAD

**Issue by wbobeirne** [cpojer/js-codemod#53]
We use tabs in our codebase, and running the trailing-commas codemod cause this block:
```
api.get({
	api_version: 1,
	path: "/settings/hiddenusers",
	query : {
		limit: 10,
		before: res.body.paging.cursors.before,
	}
})
.then(() => {
	done();
})
.catch(genericApiError(done));
```
to become
```
api.get({
    api_version: 1,
    path: "/settings/hiddenusers",

    query: {
        limit: 10,
        before: res.body.paging.cursors.before,
    },
})
.then(() => {
	done();
})
.catch(genericApiError(done));
```

Would be nice if it respected the whitespace already there!

**Comment by wbobeirne** [comment]
Not sure how I missed this before posting, but the added newlines are also something I don't think should be happening!

**Comment by cpojer** [comment]
I think this should be reported in recast: https://github.com/benjamn/recast
