### ISSUE TITLE
arrow-function-arguments performs invalid transformations

### ISSUE THREAD

**Issue by nene** [cpojer/js-codemod#64]
I was looking into the `arrow-function-arguments` transform. The functionality looked pretty useful - converting `arguments` into `...args` - but then I realized that `arguments` in arrow functions don't work like the transform assumes they do. For example the following:

```js
function foo() {
    var fn1 = () => console.log(arguments);
}
```

gets transformed into:

```js
function foo() {
    var fn1 = (...args) => console.log(args);
}
```

But `arguments` inside arrow do not function refer to the arguments of arrow function, but instead to the `arguments` in parent scope. The correct transform would be instead:

```js
function foo(...args) {
    var fn1 = () => console.log(args);
}
```

For some reason the transform does exactly the opposite of what would be the correct way. The name of the transform suggests, that this is intentional. But the intentions seem to be misguided.

**Comment by cpojer** [comment]
Yeah this does seem like a bug. We didn't create this transform with code in mind that already used arrow functions. Unfortunately this repo is more self-serve: I don't provide active support for it. If you'd like to send a PR with a fix, that would be greatly appreciated.

**Comment by nene** [comment]
Well, I was looking into this because I'd like to implement a similar transform in Lebab.

I guess I'll do a PR, but into a different project...

**Comment by cpojer** [comment]
Ok, I'll close this issue then but I'd still appreciate a PR to fix the transform in js-codemod :)
