### ISSUE TITLE
object-shorthand.js glitch

### ISSUE THREAD

**Issue by winkler1** [cpojer/js-codemod#72]
Thanks for doing these, they're great!

Having a problem with `object-shorthand.js`..

Given a Redux Action creator like this: 
```
  select: function(type: string, id: string, options: Object = {}): Object {
    ...
  },
```
object-shorthand.js is getting confused and emitting invalid code
```
select(type: string, id: string, = {}): Object {
    ...
  },
```

TLDR: `options: Object = {}` becomes `= {}`

**Comment by cpojer** [comment]
Thanks! I do not generally provide support on this repository. If you'd like to see this fixed, please send a PR with a test :) Thank you.
